modules:
  asr04:
    auth:
      community: cc-snmpcollector
    version: 1
    walk:
      [
        ntpEntStatusActiveOffset,
        ntpEntStatusDispersion,
      ]
    overrides:
      ntpEntStatusActiveOffset:
        type: gauge
      ntpEntStatusDispersion:
        type: gauge