{{- if .Values.prometheus_server.enabled }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.prometheus_server.name }}-additional-scrape-config
  labels:
    prometheus: {{ .Values.prometheus_server.name }}

data:
  scrape-config.yaml: {{ include (print $.Template.BasePath "/_prometheus.yaml.tpl") . | b64enc }}
{{- end }}