global:
  domain: cloud.sap
  region: DEFINED-IN-REGION
prometheus-pushgateway:
  nameOverride: pushgateway-infra
  enabled: false
  ingress:
    enabled: true
    hosts:
      - pushgateway-infra.scaleout
    vicePresident: true
    tls:
      enabled: true
  externalName: pushgateway-infra.infra-monitoring.svc.cluster.local
