dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.3.11
  - name: memcached
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.3
  - condition: mariadb.enabled
    name: mysql_metrics
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.3
  - name: rabbitmq
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
  - alias: rabbitmq_notifications
    condition: audit.enabled
    name: rabbitmq
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
  - name: region_check
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2
  - name: utils
    repository: file://../../openstack/utils
    version: 0.2.0
  - alias: logger-redis
    condition: logger.enabled
    name: redis
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.1
