{{- if .Values.simulator.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: cronus-simulator-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: cronus-simulator
    app.kubernetes.io/instance: cronus-simulator
{{- end -}}
