kind: Ingress
apiVersion: networking.k8s.io/v1beta1

metadata:
  name: doop-central
  annotations:
    kubernetes.io/tls-acme: "true"

spec:
  tls:
    - secretName: tls-doop-central
      hosts: [ doop.global.{{ $.Values.global.tld | required ".Values.global.tld not found" }} ]
  rules:
    - host: doop.global.{{ $.Values.global.tld | required ".Values.global.tld not found" }}
      http:
        paths:
          - path: /
            backend:
              serviceName: doop-central
              servicePort: 80
