redfish:
  enabled: false
  app_env: "production"
  image: redfish-exporter
  tag: '20210910102720'
  fullnameOverride: redfish-exporter
  listen_port: 9220
  alerts:
    enabled: true
    prometheus: infra-collector
