redfish:
  enabled: false
  app_env: "production"
  image: redfish-exporter
  tag: '20210726180018'
  fullnameOverride: redfish-exporter
  listen_port: 9220
  alerts:
    enabled: true
    prometheus: infra-collector
  limits:
      memory: 500Mi
      cpu: 1500m
  resources:
      memory: 100Mi
      cpu: 500m
