redfish:
  name: redfish-exporter
  enabled: false
  app_env: "production"
  image: redfish-exporter
  tag: '20210924145537'
  fullnameOverride: redfish-exporter
  listen_port: 9220
  namespace: infra-monitoring
  alerts:
    enabled: true
    prometheus: infra-collector

  # Prometheus operator ServiceMonitor support
prometheus:
  operator:
    ## Setting to true will create Prometheus-Operator specific resources like ServiceMonitors
    enabled: false

    ## Configures alerts for Prometheus to pick up
    prometheusRule:
      enabled: true
      ## Labels to add to alerts
      labels: {}

    ## Configures targets for Prometheus to pick up
    serviceMonitor:
      ## Interval at which Prometheus will scrape metrics exporter
      interval: 10m
      ## Timeout after which the scrape is ended
      scrapeTimeout: 9m
