{{- if .Values.maia.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maia
  namespace: maia
  labels:
    system: openstack
    service: metrics

spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      component: maia
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        component: maia
      annotations:
        checksum/maia-templates-maia-configmap.yaml: {{ include "maia/templates/maia-configmap.yaml" . | sha256sum }}
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: maia-etc
          configMap:
            name: maia
        {{- if .Values.cronus.enabled }}
        - name: prometheus-infra-cert
          secret:
            secretName: cronus-prometheus-infra-sso-cert
            items:
            - key: sso.crt
              path: /etc/prometheus/secrets/prometheus-infra-sso-cert/sso.crt
        - name: prometheus-infra-key
          secret:
            secretName: cronus-prometheus-infra-sso-cert
            items:
            - key: sso.key
              path: /etc/prometheus/secrets/prometheus-infra-sso-cert/sso.key
        {{ end }}
      containers:
        - name: maia
          # remove the "string:" prefix which is used to prevent helm's --set option from reformatting plain numbers into floats in scientific notation
          image: {{ required "maia.docker_repo variable is missing" .Values.maia.docker_repo }}:{{ required "maia.image_version variable missing" .Values.maia.image_version }}
          imagePullPolicy: IfNotPresent
#          command: ["sh"]
#          args:
#           - -c
#           - "ls /etc/maia; sleep 10000"
          args: ["serve"]
          env:
            - name: MAIA_DEBUG
              value: {{ $.Values.maia.debug | quote }}
          resources:
              requests:
                  memory: {{ .Values.maia.resources.memory.expected }}
                  cpu: {{ .Values.maia.resources.cpu.expected }}
              limits:
                  memory: {{ .Values.maia.resources.memory.tolerated }}
                  cpu: {{ .Values.maia.resources.cpu.tolerated }}
          volumeMounts:
            - mountPath: /etc/maia
              name: maia-etc
            {{- if .Values.cronus.enabled }}
            - mountPath: /etc/prometheus/secrets/prometheus-infra-sso-cert/sso.crt
              name: prometheus-infra-cert
            - mountPath: /etc/prometheus/secrets/prometheus-infra-sso-cert/sso.key
              name: prometheus-infra-key
            {{ end }}
          ports:
            - name: api
              containerPort: {{ .Values.maia.listen_port }}
{{- end }}
