{{- $values := .Values.alerts }}
{{- if $values.enabled }}
{{- range $path, $bytes := .Files.Glob "alerts/*.alerts" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ printf "cc3test-%s" $path | replace "/" "-" }}
  labels:
    app: apic-exporter
    prometheus: {{ required "$values.prometheus missing" $values.prometheus }}

spec:
{{ printf "%s" $bytes | indent 2 }}

{{- end }}
{{- end }}
