apiVersion: v1
kind: Secret

metadata:
  name: cc3test-secrets
stringData:
  secrets.yaml: |
    cc3test:
{{ toYaml .Values.cc3test.secrets | indent 6 }}
{{ toYaml .Values.cc3test.authentication | indent 6 }}