apiVersion: v1
kind: Secret

metadata:
  name: cc3test-secrets
stringData:
  secrets.yaml: |
    secrets:
{{ toYaml .Values.secrets | indent 6 }}
    authentication:
{{ toYaml .Values.authentication | indent 6 }}