apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: cc3test-seed
  labels:
    component: cc3test
spec:
  requires:
#  - keystone-seed
  - monsoon3/domain-cc3test-seed
  - monsoon3/domain-ccadmin-seed
  - monsoon3/domain-default-seed

  roles:
  - name: cloud_compute_admin
  - name: cloud_network_admin
  - name: cloud_dns_admin
  - name: cloud_image_admin
  - name: cloud_keymanager_admin
  - name: cloud_resource_admin
  - name: cloud_sharedfilesystem_admin
  - name: cloud_volume_admin
  - name: cloud_baremetal_admin

  domains:
  - name: {{ default "Default" .Values.cc3test.service_user.user_domain_name | quote}}
    users:
    - name: {{ default "cc3test" .Values.cc3test.service_user.name | quote }}
      description: 'cc3test service user'
      password: {{ .Values.cc3test.service_user.password | quote }}
      role_assignments:
      - project: cloud_admin@ccadmin
        role: admin
      - project: cloud_admin@ccadmin
        role: cloud_compute_admin
      - project: cloud_admin@ccadmin
        role: cloud_dns_admin
      - project: cloud_admin@ccadmin
        role: cloud_image_admin
      - project: cloud_admin@ccadmin
        role: cloud_keymanager_admin
      - project: cloud_admin@ccadmin
        role: cloud_network_admin
      - project: cloud_admin@ccadmin
        role: cloud_resource_admin
      - project: cloud_admin@ccadmin
        role: cloud_sharedfilesystem_admin
      - project: cloud_admin@ccadmin
        role: cloud_volume_admin
      - project: cloud_admin@ccadmin
        role: cloud_baremetal_admin
      - domain: Default
        role: admin
      - domain: ccadmin
        role: admin
