{{- $envAll := . }}
{{- range $name, $val := .Values.workers -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: octavia-etc-{{ $name }}
  labels:
    system: openstack
    type: configuration
    component: octavia

data:
  octavia-worker.conf: |
{{ tuple $envAll $name $val | include "octavia_worker_conf" | indent 4 }}
  octavia-change-pw.sh: |
{{ tuple $envAll $val | include "octavia_worker_change_pw" | indent 4 }}
{{ end }}