# Default values for maintenance-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
image:
  repository: sapcc/maintenance-controller
  tag: 0.1
  pullPolicy: IfNotPresent
slack:
  webhook:
  channel:
rbac:
  create: false
  serviceAccountName: default
