apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    system: openstack
    service: monitoring
    component: monasca-grafana
spec:
  clusterIP: None
  selector:
    component: grafana
  ports:
    - port: {{.Values.grafana.port.public}}
