apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  labels:
    system: openstack
    service: monitoring
    component: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: grafana
      annotations:
        checksum/grafana.etc: {{ include "grafana-test/templates/grafana-etc-configmap.yaml" . | sha256sum }}
        checksum/grafana.bin: {{ include "grafana-test/templates/grafana-bin-configmap.yaml" . | sha256sum }}
        checksum/grafana.ini: {{ include "grafana-test/templates/_grafana.ini.tpl" . | sha256sum }}
        checksum/ldap.toml: {{ include "grafana-test/templates/_ldap.toml.tpl" . | sha256sum }}
        checksum/grafana-start: {{ include "grafana-test/templates/_grafana-start.tpl" . | sha256sum }}
        checksum/grafana-initial-setup: {{ include "grafana-test/templates/_grafana-initial-setup.tpl" . | sha256sum }}
        checksum/helpers: {{ include "grafana-test/templates/_helpers.tpl" . | sha256sum }}
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: grafana-bin
          configMap:
            name: grafana-bin
        - name: grafana-etc
          configMap:
            name: grafana-etc
        - name: grafana-content
          emptyDir: {}
      containers:
        - name: "grafana"
          image: {{.Values.grafana.image}}:{{.Values.grafana.image_version}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          command:
            - /bin/bash
          args:
            - /grafana-bin/grafana-start
          env:
            - name: GF_PATHS_PROVISIONING
              value: "/var/lib/grafana/provisioning"
          ports:
            - name: nodejs
              containerPort: 3000
          volumeMounts:
            - name: grafana-bin
              mountPath: /grafana-bin
            - name: grafana-etc
              mountPath: /grafana-etc
            - name: grafana-content
              mountPath: /git
        - name: "gitsync"
          image: hub.global.cloud.sap/monsoon/git-sync:v2_0_6
          imagePullPolicy: {{.Values.image.pullPolicy}}
          args:
            - "--repo=https://github.wdf.sap.corp/monsoon/grafana-content"
            - "--branch=gitsync"
            - "--wait=30"
          env:
            - name: GIT_SSL_NO_VERIFY
              value: "true"
          volumeMounts:
            - name: grafana-content
              mountPath: /git
