---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-bin
  labels:
    system: openstack
    service: monitoring
    component: configuration

data:
  grafana-start: |
{{ include "grafana-test/templates/_grafana-start.tpl" . | indent 4 }}
  grafana-initial-setup: |
{{ include "grafana-test/templates/_grafana-initial-setup.tpl" . | indent 4 }}
  postgres-start: |
{{ include "grafana-test/templates/_postgres-start.tpl" . | indent 4 }}
