---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-etc
  labels:
    system: openstack
    service: monitoring
    component: configuration

data:
  grafana.ini: |
{{ include "grafana-test/templates/_grafana.ini.tpl" . | indent 4 }}
  ldap.toml: |
{{ include "grafana-test/templates/_ldap.toml.tpl" . | indent 4 }}
  create-session-table.sql: |
{{ include "grafana-test/templates/_create-session-table.sql.tpl" . | indent 4 }}
