kind: Ingress
apiVersion: networking.k8s.io/v1beta1

metadata:
  name: nova-api
  labels:
    system: openstack
    type: api
    component: nova
  {{- if .Values.use_tls_acme }}
  annotations:
    kubernetes.io/tls-acme: "true"
  {{- end }}
spec:
  tls:
     - secretName: tls-{{include "nova_api_endpoint_host_public" . | replace "." "-" }}
       hosts: [{{include "nova_api_endpoint_host_public" .}}]
  rules:
    - host: {{include "nova_api_endpoint_host_public" .}}
      http:
        paths:
        - path: /
          backend:
            serviceName: nova-api
            servicePort: {{.Values.global.novaApiPortInternal}}
