kind: Ingress
apiVersion: networking.k8s.io/v1beta1

metadata:
  name: nova-console
  labels:
    system: openstack
    type: backend
    component: nova
  annotations:
    ingress.kubernetes.io/use-regex: "true"
    ingress.kubernetes.io/configuration-snippet: |
      {{- range $name, $config := .Values.consoles }}
      rewrite "(?i)/{{ $name }}/(.*)" /$1 break;
      rewrite "(?i)/{{ $name }}$" / break;
      {{- end }}
  {{- if .Values.use_tls_acme }}
    kubernetes.io/tls-acme: "true"
  {{- end }}
spec:
  tls:
  - secretName: tls-{{include "nova_console_endpoint_host_public" . | replace "." "-" }}
    hosts: [{{include "nova_console_endpoint_host_public" .}}]
  rules:
  - host: {{include "nova_console_endpoint_host_public" .}}
    http:
      paths:
      {{- range $name, $config := .Values.consoles }}
      - path: /{{ $name }}/?(.*)
        backend:
          serviceName: nova-console-{{ $name }}
          servicePort: {{ $name }}
      {{- end }}

{{ $envAll := . }}
{{- range $name, $config := .Values.consoles }}
---
{{ tuple $envAll $name $config | include "nova.console_service"  }}
{{- end }}
