global:
  region: DEFINED-AS-VALUE
  domain: DEFINED-AS-VALUE

prometheus:
  image: prom/prometheus
  tag: v2.8.0

cloudprober-exporter:
  enabled: false

netapp-exporter:
  enabled: false

apic_exporters:
  enabled: false

arista_exporter:
  enabled: false
  configmap_name: arista-sd
