apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-ntp-exporter
data:
  snmp-ntp-exporter.yaml:
{{- if .Values.global.asr04.enabled }}
    asr04:
{{ .Files.Get "_snmp-exporter-asr04.yaml" | indent 4}}
      version: {{ .Values.snmp_exporter.asr04.version }}
      max_repetitions: 25
      retries: 3
      timeout: 10s
      auth:
        security_level: {{ .Values.snmp_exporter.asr04.security_level }}
        username: {{ .Values.snmp_exporter.asr04.username }}
        password: {{ .Values.snmp_exporter.asr04.password }}
        auth_protocol: {{ .Values.snmp_exporter.asr04.auth_protocol }}
        priv_protocol: {{ .Values.snmp_exporter.asr04.priv_protocol }}
        priv_password: {{ .Values.snmp_exporter.asr04.priv_password }}
{{- end }}
{{- if .Values.global.n7k.enabled }}
    n7k:
{{ .Files.Get "_snmp-exporter-n7k.yaml" | indent 4}}
      version: {{ .Values.global.n7k.version }}
      max_repetitions: 25
      retries: 3
      timeout: 10s
      auth:
        security_level: {{ .Values.global.n7k.security_level }}
        username: {{ .Values.global.n7k.username }}
        password: {{ .Values.global.n7k.password }} 
        auth_protocol: {{ .Values.global.n7k.auth_protocol }}
        priv_protocol: {{ .Values.global.n7k.priv_protocol }}
        priv_password: {{ .Values.global.n7k.priv_password }}
{{- range $switch := .Values.global.n7k.context }}
    n7k{{ $switch.context_name | lower }}:
{{ $.Files.Get "_snmp-exporter-n7kcontext.yaml" | indent 4}}
      version: {{ $switch.version }}
      max_repetitions: 25
      retries: 3
      timeout: 10s
      auth:
        security_level: {{ $switch.security_level }}
        username: {{ $switch.username }}
        password: {{ $switch.password }} 
        auth_protocol: {{ $switch.auth_protocol }}
        priv_protocol: {{ $switch.priv_protocol }}
        priv_password: {{ $switch.priv_password }}
        context_name: {{ $switch.context_name }}
{{- end }}
{{- else if .Values.snmp_exporter.n7k.community }}
    n7k:
{{ $.Files.Get "_snmp-exporter-n7k.yaml" | indent 4}}
      version: {{ .Values.snmp_exporter.n7k.version }}
      auth:
        community: {{ .Values.snmp_exporter.n7k.community }}
{{- end }}