apiVersion: v2
appVersion: "1.0"
description: Kubernetes virtual cluster monitoring.
name: kube-monitoring-virtual
version: 0.10.8
dependencies:
  - condition: absent-metrics-operator.enabled
    name: absent-metrics-operator
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.7.0
  - name: event-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.4
  - name: fluent-bit
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 2.7.2
  - name: grafana-dashboards-kubernetes
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.6
  - name: k8s-secrets-certificate-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.3.2
  - name: kube-state-metrics
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 2.8.4
  - name: kube-state-metrics-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.7
  - name: kubernikus-monitoring
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.1.7
  - name: ntp-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 2.0.0
  - name: oomkill-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.9
  - name: ping-exporter
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.1
  - name: prometheus-crds
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.0
  - name: prometheus-kubernetes-rules
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.2.7
  - name: prometheus-node-exporter
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.9.1
  - name: prometheus-operator
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 8.3.1
  - name: prometheus-server
    repository: https://charts.eu-de-2.cloud.sap
    version: 3.7.3
  - name: prometheus-virtual-rules
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.1
