{{- if contains ",f5" .Values.ml2_mechanismdrivers }}
{{- range $loadbalancer := .Values.new_f5.loadbalancers }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-f5-agent-{{$loadbalancer.name}}
  labels:
    system: openstack
    type: configuration
    component: neutron

data:
  f5-agent.conf.ini: |
{{ tuple $ $loadbalancer | include "f5_agent_conf_ini" | indent 4 }}

  f5_change_pw.sh: |
    #!/bin/sh

{{ tuple $ $loadbalancer.hosts | include "f5_change_pw" | indent 4 }}
{{ tuple $ (keys $loadbalancer.vcmp_host_guest_mapping) | include "f5_change_pw" | indent 4 }}

{{- end }}
{{- end }}