dependencies:
  - name: prometheus-node-exporter
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.3.0
  - name: kube-state-metrics
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.8.1
