global:
  region: DEFINED-AS-VALUE
  domain: DEFINED-AS-VALUE

  clusterType: controlplane

  prometheus:
    image: prom/prometheus
    tag: v2.8.0

  configmap_reload:
    image:
      repository: jimmidyson/configmap-reload
      tag: v0.2.2

  ipmi_service_discovery:
    enabled: false
    configmap_name: ipmi-sd
    netbox:
      enabled: false
    #api_token:

  ipmi_exporter:
    enabled: false
    netbox:
      enabled: false

  arista_exporter:
    enabled: false
    configmap_name: arista-sd

  # placeholder. the full list of regions is set via the pipeline
  regions:
    - "staging"

  # Prometheus via deployment.
  prometheus_deploy:
    enabled: true

  # Prometheus via operator.
  prometheus_operated:
    enabled: false

# Values for operated Prometheus collector.
# Only used if global.prometheus_operated.enabled: true.
prometheus-collector-operated:
  name: k8s-collector

  retentionTime: 1h

  additionalScrapeConfigs:
    name: k8s-collector-additional-scrape-config
    key: scrape-config.yaml

  ingress:
    enabled: false

  # Store in memory.
  persistence:
    enabled: false

  serviceAccount:
    create: false
    name: default

  serviceDiscoveries:
    endpoints:
      enabled: false

# Values for operated Prometheus frontend.
# Only used if global.prometheus_operated.enabled: true.
prometheus-frontend-operated:
  name: k8s-frontend

  retentionTime: 1h

  additionalScrapeConfigs:
    name: k8s-frontend-additional-scrape-config
    key: scrape-config.yaml

  ingress:
    enabled: false

  # Store in memory.
  persistence:
    enabled: true
    size: 300Gi

  serviceAccount:
    create: false
    name: default

  serviceDiscoveries:
    endpoints:
      enabled: false

prometheus-node-exporter:
  image:
    repository: prom/node-exporter
    tag: v0.17.0

  serviceAccount:
    create: false
    name: default

  rbac:
    create: false

  extraArgs:
    - --collector.filesystem.ignored-mount-points=\"^/(sys|proc|dev|host|etc)($|/)\"
    - --collector.processes
    # enabled by default. flag didn't make it to prom/node-exporter:v0.17.0 .
    #- --collector.systemd.enable-task-metrics

  extraHostVolumeMounts:
    - name: dbus
      hostPath: /var/run/dbus/system_bus_socket
      mountPath: /var/run/dbus/system_bus_socket
      readOnly: true

  resources:
    requests:
      memory: 100Mi
      cpu: 100m

kube-state-metrics:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/port_1: "8081"

  image:
    repository: sapcc/kube-state-metrics

  rbac:
    create: false
    serviceAccountName: default

  collectors:
    # not useful
    configmaps: false
    secrets: false
    # not available in k8s1.7
    cronjobs: false
    horizontalpodautoscalers: false

  resources:
    requests:
      memory: 150Mi
      cpu: 100m

fluent-bit:
  enabled: false

  image:
    fluent_bit:
      repository: fluent/fluent-bit
      tag: 1.0.4
    pullPolicy: IfNotPresent

  backend:
    es:
      tls_ca: ""
      # host:
      # http_user:
      # http_passwd:
      # logstash_prefix:

  # filter:
  # list of additional static values added to each log entry
  #  additionalValues:
  #  - key: some-key
  #    value: some-value

  podAnnotations:
    # manual versioning, raise if configmap changes
    versioning: "1"

  existingConfigMap: fluent-bit-config

  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

  rbac:
    create: true

  serviceAccount:
    create: true
