---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-nova-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ if .Values.global.region | require ".Values.global.region missing" | regexMatch "^(?:ap-au-1|eu-de-[12]|eu-nl-1|na-us-1)$" -}} 100Gi {{- else -}} 50Gi {{- end }}
