---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-octavia-pvclaim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ if .Values.global.region | required ".Values.global.region missing" | regexMatch "^(?:ap-sa-2)$" -}} 50Gi {{- else -}} 10Gi {{- end }}
