---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ironic-tftp-pvclaim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      {{- $region := .Values.global.region | required ".Values.global.region missing" }}
      storage: {{ if $region | regexMatch "^(?:ap-au-1|eu-nl-1)$" -}} 1Gi {{- else -}} 100Gi {{- end }}
