---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nova
    release: nova
  name: nova-vspc-pvclaim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
