kind: Secret
apiVersion: v1
metadata:
  name: logstash-secret
  namespace: hermes
  labels:
    system: openstack
    service: audit
stringData:
  # If a region is not configured, default value
  METIS_PASSWORD: {{ default "default" .Values.global.metis.password }}