image:
  repository: sapcc/k8s-secrets-certificate-exporter
  tag: v201904111325
  pullPolicy: IfNotPresent

# Port to expose Prometheus metrics on.
metricsPort:      9091

# Interval for secret synchronization.
resyncInterval:   15m

# Interval for checking secrets.
recheckInterval:  30m

# If set only secrets in the given namespace are considers. Default all namespaces (`"`).
namespace: ""

# Exporter threadiness.
threadiness:      1

# Creating RBAC resources.
rbac:
  create: false
  serviceAccountName: default
