docker_repo: keppel.eu-de-1.cloud.sap/ccloud/snmp-ntp-exporter
image_version: latest
global:
  n7k:
    enabled: false
  asa:
    enabled: false
snmp_exporter:
  listen_port: 9116
  replicas: 2
  scrapeInterval: 1m
  scrapeTimeout: 55s
  fullnameOverride: snmp-ntp-exporter
  asr04:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
  n7k:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS