{{- if .Values.cinder_nanny.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: cinder-nanny-secret
data:
  cinder_nanny_os_password: {{ derivePassword 1 "long" .Values.nannies.master_password "cinder_nanny" (include "keystone_api_endpoint_host_public" .) | quote }}
  nova_nanny_os_password: {{ derivePassword 1 "long" .Values.nannies.master_password "nova_nanny" (include "keystone_api_endpoint_host_public" .) | quote }}
{{- end }}
