apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: nanny-seed
spec:
  requires:
  - monsoon3/domain-default-seed
  - monsoon3/domain-ccadmin-seed

  domains:
  - name: Default
    users:
    - name: vcenter_nanny
      description: Vcenter Nanny
      valueFrom:
        secretKeyRef:
           name: vcenter-nanny-secret
           key:  vcenter_nanny_os_password
    - name: nova_nanny{{ .Values.global.user_suffix | default "" }}
      description: Nova Nanny
      valueFrom:
        secretKeyRef:
           name: nova-nanny-secret
           key:  nova_nanny_os_password
    - name: cinder_nanny{{ .Values.global.user_suffix | default "" }}
      description: Cinder Nanny
      valueFrom:
        secretKeyRef:
           name: cinder-nanny-secret
           key:  cinder_nanny_os_password

  - name: ccadmin
    projects:
    - name: cloud_admin
      role_assignments:
      # permission to enumerate all projects and domains
      - user: vcenter_nanny@Default
        role: admin
      # permission to manage all ressources checked by the nanny
      - user: vcenter_nanny@Default
        role: cloud_compute_admin
      - user: vcenter_nanny@Default
        role: cloud_volume_admin
      - user: vcenter_nanny@Default
        role: cloud_image_admin
      - user: vcenter_nanny@Default
        role: cloud_network_admin
      # permission to enumerate all projects and domains
      - user: nova_nanny{{ .Values.global.user_suffix | default "" }}@Default
        role: admin
      # permission to manage all ressources checked by the nanny
      - user: nova_nanny{{ .Values.global.user_suffix | default "" }}@Default
        role: cloud_compute_admin
      - user: nova_nanny{{ .Values.global.user_suffix | default "" }}@Default
        role: cloud_volume_admin
      # permission to enumerate all projects and domains
      - user: cinder_nanny{{ .Values.global.user_suffix | default "" }}@Default
        role: admin
      # permission to manage all ressources checked by the nanny
      - user: cinder_nanny{{ .Values.global.user_suffix | default "" }}@Default
        role: cloud_volume_admin
      - user: cinder_nanny{{ .Values.global.user_suffix | default "" }}@Default
        role: cloud_compute_admin
