{{- if .Values.vm_balance_nanny.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: vm-balance-nanny-secret
data:
  {{- if .Values.promauth.ssoCert }}
  client_cert: {{ .Values.promauth.ssoCert | b64enc }}
  {{- end }}
  {{- if .Values.promauth.ssoKey }}
  client_key: {{ .Values.promauth.ssoKey | b64enc }}
  {{- end }}
{{- end }}
