{{- if .Capabilities.APIVersions.Has "vcenter-operator.stable.sap.cc/v1" }}
{{- if .Values.vm_balance_nanny.enabled }}
kind: VCenterTemplate
apiVersion: vcenter-operator.stable.sap.cc/v1
metadata:
  name: 'vcenter-datacenter-vm-balance-secrets'
options:
  scope: 'datacenter'
  jinja2_options:
    variable_start_string: '{='
    variable_end_string: '=}'
template: |
  kind: Secret
  apiVersion: v1
  metadata:
    name: vm-balance-nanny-{= name =}
  data:
    {{- if .Values.nannies.vcenter_username | default "" }}
    vm_balance_vcpassword: {= "{{ .Values.nannies.vcenter_username }}" | derive_password | b64enc =}
    {{- else }}
    vm_balance_vcpassword: {= password | b64enc =}
    {{- end }}
    {{- if .Values.promauth.ssoCert }}
    client_cert: {{ .Values.promauth.ssoCert | b64enc }}
    {{- end }}
    {{- if .Values.promauth.ssoKey }}
    client_key: {{ .Values.promauth.ssoKey | b64enc }}
    {{- end }}
  {{- end }}
  {{- end }}
