dependencies:
  - name: redis
    alias: sapcc-ratelimit-redis
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.1.1
    condition: sapcc_ratelimit.enabled
  - name: owner-info
    repository: file://../../common/owner-info
    version: 0.1.0
