image_tag: 791722aca5 # Git commit for <https://github.com/sapcc/gatekeeper-addons>

# NOTE: This section is shared with the `system/gatekeeper` chart.
doop:
  # values with default value null must be provided by values.yaml
  swift_password: null
