kind: Deployment
apiVersion: apps/v1

metadata:
  name: validation
  namespace: cc3test

spec:
  replicas: 1
  selector:
    matchLabels:
      name: validation
  template:
    metadata:
      labels:
        name: validation
        checksum/configmap: {{ include "validation/templates/configmap.yaml" $ | sha256sum }}
    spec:
      volumes:
        - name: cc3test-config
          configMap:
            name: cc3test-config
        - name: validation-config
          configMap:
            name: validation-config
        - name: cc3test-secrets
          secret:
            secretName: cc3test-secrets
      containers:
        - name: validation
          image: {{ required ".Values.global.registry variable missing" .Values.global.registry }}/{{ required ".Values.cc3test.image.name variable missing" .Values.cc3test.image.name }}:{{ required ".Values.cc3test.image.tag variable missing" .Values.cc3test.image.tag }}
          command: ["/bin/sh"]
          args: ["-c", "while true; do date; sleep 5; done"]
          volumeMounts:
            - name: cc3test-config
              mountPath: /cc3test/config
              readOnly: true
            - name: validation-config
              mountPath: /validation/config
              readOnly: true
            - name: cc3test-secrets
              mountPath: /cc3test/secrets
              readOnly: true