{{- if and .Values.global.prometheus_deploy.enabled .Values.tls_crt }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: prometheus-frontend

data:
  tls.crt: {{ default "" .Values.tls_crt | b64enc | quote }} 
  tls.key: {{ default "" .Values.tls_key | b64enc | quote }}
{{- end }}
