{{- if .Values.global.prometheus_deploy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus-frontend
spec:
  selector:
    app: prometheus
    type: frontend
  ports:
    - port: 9090
{{- end }}
