apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-global

data:
  {{- $files := .Files }}
  {{ range tuple "interconnect.alerts" "prometheus.alerts" "ca.crt" }}
  {{ . }}: |
{{ $files.Get . | indent 4 }}
  {{- end }}
  prometheus.yaml: |
{{ include "prometheus/templates/_prometheus.yaml.tpl" . | indent 4 }}
