image:
  # Configure the registry for all VPA images.
  # Default: k8s.gcr.io
  # In Converged Cloud we use our in-house image registry.
  registry: keppel.global.cloud.sap/ccloud-k8sgcr-mirror

# The recommender is always enabled.
recommender:
  image:
    # The full image will be $registry/$repository:$tag.
    repository: autoscaling/vpa-recommender

admission:
  enabled: false
  image:
    # The full image will be $registry/$repository:$tag.
    repository: autoscaling/vpa-admission-controller

updater:
  enabled: false
  image:
    # The full image will be $registry/$repository:$tag.
    repository: autoscaling/vpa-updater
