{{- if .Values.elasticsearch_exporter.enabled }}
{{- range $i, $config := .Values.elasticsearch_exporter.elasticsearch_config -}}
{{ if ne $i 0 }}---{{ end }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-exporter-{{$config.name}}
  namespace: elk
  labels:
    system: openstack
    service: logging

spec:
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        component: elasticsearch-exporter-{{$config.name}}
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: elasticsearch-exporter
          image: justwatch/elasticsearch_exporter:{{ $.Values.elk_image_version_elasticsearch_exporter }}
          imagePullPolicy: IfNotPresent
          command: [ "/bin/elasticsearch_exporter", "-es.uri", "{{$config.protocol}}://{{ if $config.auth }}{{$config.username }}:{{$config.password }}@{{ end }}{{$config.hostname}}:{{$config.port}}" , "-es.all", "-web.listen-address", ":{{ $.Values.elasticsearch_exporter.listen_port }}" ]
          ports:
            - name: metrics
              containerPort: {{ $.Values.elasticsearch_exporter.listen_port }}
{{ end -}}
{{ end -}}
