apiVersion: v1
kind: Service
metadata:
  name: es-client
  namespace: elk
  labels:
    system: openstack
    service: logging
    component: elasticsearch
    role: client
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: {{.Values.elk_elasticsearch_port_internal}}
  type: LoadBalancer
