apiVersion: v1
kind: Service
metadata:
  name: es-daya
  namespace: elk
  labels:
    system: openstack
    service: logging
    component: elasticsearch
    role: data
spec:
  clusterIP: None
  selector:
    component: elasticsearch
    role: data
  ports:
  - name: http
    port: {{.Values.elk_elasticsearch_port_internal}}
    protocol: TCP
