{{- if .Values.fluentd_systemd.enabled }}
kind: DaemonSet
apiVersion: extensions/v1beta1

metadata:
  name: fluent-systemd
  namespace: elk
  annotations:
    kubernetes.io/change-cause: {{.Values.cluster_deployment_reason}}
spec:
  minReadySeconds: 15
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: fluent-systemd
      annotations:
        checksum/elk-templates-fluent-systemd-etc-configmap.yaml: {{ include "elk/templates/fluent-systemd-etc-configmap.yaml" . | sha256sum }}
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"species","value":"hypervisor"}]'
    spec:
      {{- if ge .Capabilities.KubeVersion.Minor "7" }}
      tolerations:
      - key: "species"
        operator: "Exists"
        effect: "NoSchedule"
      {{- end }}
      volumes:
        - name: fluent-etc
          configMap:
            name: fluent-systemd-etc
        - name: varlog
          hostPath:
            path: /var/log
      containers:
        - name: fluent-systemd
          image: {{.Values.docker_repo}}/elk-fluent:{{.Values.elk_image_version_fluent}}
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/dumb-init", "/usr/local/bin/fluentd", "-c", "/fluent-etc/fluent.conf", "--use-v1-config", "--suppress-repeated-stacktrace"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEPENDENCY_SERVICE
              value: "{{.Values.elk_elasticsearch_endpoint_host_internal}}"
          resources:
#            limits:
#              cpu: 1000m
#              memory: 2000Mi
          volumeMounts:
            - name: fluent-etc
              mountPath: /fluent-etc
            - name: varlog
              mountPath: /var/log
          ports: 
            - name: fluent
              containerPort: {{.Values.elk_fluent_systemd_port}}
              hostPort: {{.Values.elk_fluent_systemd_port}}
              hostIP: 127.0.0.1
{{- end }}
