apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: prometheus-alertmanager

spec:
  revisionHistoryLimit: 5
  replicas: 1 
  selector:
    matchLabels:
      app: prometheus
      type: alertmanager
  template:
    metadata:
      labels:
        app: prometheus
        type: alertmanager
    spec:
      nodeSelector:
        zone: farm
      terminationGracePeriodSeconds: 300
      containers:
        - name: prometheus 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --web.external-url=https://alertmanager.{{.Values.global.region}}.{{.Values.global.domain}}
            - --log.level={{ default "info" .Values.log_level }}
            - --cluster.listen-address=:{{.Values.cluster.listen_address}}
            - --cluster.peer-timeout={{ .Values.cluster.peer_timeout }}
            - --cluster.probe-timeout={{ .Values.cluster.probe_timeout }}
            - --cluster.tcp-timeout={{ .Values.cluster.tcp_timeout }}
            {{- range .Values.cluster.peers }}
            - --cluster.peer={{ . }}
            {{- end }}
          ports:
            {{- if .Values.cluster.listen_address }}
            - name: cluster
              containerPort: {{.Values.cluster.listen_address}}
            {{- end }}
            - name: http
              containerPort: 9093
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
      volumes:
        - name: config
          configMap:
            name: prometheus-alertmanager
