apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager
  annotations:
      prometheus.io/port: "9093"
      prometheus.io/scrape: "true"
spec:
  selector:
    app: prometheus
    type: alertmanager
  ports:
    - name: http
      port: 9093
    - name: cluster
      port: {{ default 8000 .Values.cluster.listen_address }}
  {{ if .Values.external_ip }}
  externalIPs:
      - {{ .Values.external_ip | quote }}
  {{ end }}