{{- if .Values.updater.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronus-updater
  {{- if .Values.updater.annotations }}
  annotations:
    {{ toYaml .Values.updater.annotations | indent 4 }}
  {{- end  }}
  {{- if .Values.updater.labels }}
  labels:
    {{ toYaml .Values.updater.labels | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.updater.replicas }}
  strategy:
    type: {{ .Values.updater.updateStrategy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cronus-updater
      app.kubernetes.io/instance: cronus-updater
  template:
    metadata:
      annotations:
        checksum/config: {{ include "cronus-updater/templates/_config.yaml.tpl" . | sha256sum }}
      labels:
        app.kubernetes.io/name: cronus-updater
        app.kubernetes.io/instance: cronus-updater
    spec:
      serviceAccountName: cronus-updater
      containers:
        - name: cronus-updater
          image: "{{ .Values.updater.image.name }}:{{ .Values.updater.image.tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - "-config=/cronus-updater/config.yaml"
          volumeMounts:
            - name: cronus-updater-config
              mountPath: "/cronus-updater/config.yaml"
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - name: cronus-updater-config
          secret:
            secretName: cronus-updater-config
{{ end -}}
