{{- if .Values.updater.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: cronus-updater-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: cronus-updater
    chart: cronus-updater
    release: cronus-updater
    heritage: {{ .Release.Service }}
type: Opaque
data:
  config.yaml: {{ include "cronus-updater/templates/_config.yaml.tpl" . | b64enc }}
{{- end -}}
