global:
  region: regionOne
  domain: evil.corp

authentication:
  enabled: true
  ssoCert: "valid certificate"
  ssoKey: "valid private key"

grafana:
  admin:
    username: admin
    password: topSecret!
  sidecar:
    notifiers:
      enabled: true

extraScrapeConfig: |
  - job_name: 'dummy'
