owner-info:
  maintainers:
    - Arno Uhlig
    - Jan Knipper
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/global/git-cert-shim

git:
  repository: DEFINED_IN_VALUES_FILE
  ssh_key:    DEFINED_IN_VALUES_FILE
