{{- if and .Values.mariadb.restore.enabled .Values.mariadb.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: "datahub-restore-alerts"
  namespace: datahub
  labels:
    app.kubernetes.io/name: datahubdb
    helm.sh/chart: {{ include "datahub.chart" $ }}
    app.kubernetes.io/instance: datahubdb-{{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    prometheus: "kubernetes"

spec:
  groups:
{{ include (print .Template.BasePath "/alerts/_restorejob.alerts.tpl") . | indent 2 }}
{{- end }}
---

{{- if and .Values.backup_v2.alerts.enabled .Values.backup_v2.enabled}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: datahub-replication-alerts
  namespace: datahub
  labels:
    app.kubernetes.io/name: datahubdb
    helm.sh/chart: {{ include "datahub.chart" $ }}
    app.kubernetes.io/instance: datahubdb-{{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    prometheus: {{ required ".Values.backup_v2.alerts.prometheus missing"  .Values.backup_v2.alerts.prometheus }}

spec:
  groups:
{{ include (print .Template.BasePath "/alerts/_replication.alerts.tpl") . | indent 2 }}
{{- end }}