kind: ConfigMap
apiVersion: v1

metadata:
  name: owner-of-{{ .Release.Name }}
  labels:
    {{- if not (eq 0 (len .Values.maintainers)) }}
    primary-maintainer: {{ index .Values.maintainers 0 }}
    {{- end }}

data:
  {{- if not (eq 0 (len .Values.maintainers)) }}
  maintainers: {{ .Values.maintainers }}
  {{- end }}
