{{- if .Values.cc3test_cert.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  name: noop-digicert-cc3test
  annotations:
    kubernetes.io/ingress.class: "noop.vice_president"
    kubernetes.io/tls-acme: "true"

spec:
  backend:
    serviceName: quay-enterprise
    servicePort: 9090
  tls:
    - secretName: cc3test-digicert
      hosts: [cc3test.global.cloud.sap, 130.214.232.69, 130.214.232.70]
{{- end }}