apiVersion: v2
name: concourse-main
description: An umbrella chart for concourse ci
type: application
version: 7.6.0
appVersion: 7.6.0
dependencies:
- name: concourse
  version: 16.1.2
  repository: "https://concourse-charts.storage.googleapis.com"
- name: ingress-nginx
  version: 4.0.11
  repository: "https://kubernetes.github.io/ingress-nginx"
  condition: gitResourceProxy.enabled
