worker:
  nameOverride: ""
  name: concourse-worker

concourse:
  image: keppel.eu-de-2.cloud.sap/ccloud-dockerhub-mirror/concourse/concourse
  imageTag: "7.6.0"

  concourse:
    web:
      clusterName: "Concourse CI"
      defaultBuildLogsToRetain: "50"
      maxBuildLogsToRetain: "100"
      enableBuildAuditing: true
      enableContainerAuditing: true
      enableJobAuditing: true
      enablePipelineAuditing: true
      enableResourceAuditing: true
      enableSystemAuditing: true
      enableTeamAuditing: true
      enableWorkerAuditing: true
      enableVolumeAuditing: true
      enableRedactSecrets: true
      encryption:
        enabled: true
      kubernetes:
        enabled: true
        namespacePrefix: concourse-
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      auth:
        duration: 72h
        mainTeam:
          localUser: "admin"

  web:
    enabled: true
    replicas: 2
    service:
      annotations:
        prometheus.io/targets: "kubernetes"
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
    nodeSelector:
      ccloud.sap.com/nodepool: "ci-system"
    tolerations:
      - key: "ci"
        operator: Equal
        value: "system"
        effect: "NoSchedule"

  persistence:
    enabled: false

  worker:
    enabled: false

  postgresql:
    enabled: true
    image:
      registry: keppel.eu-de-2.cloud.sap
      repository: ccloud-dockerhub-mirror/bitnami/postgresql
      tag: 11.14.0-debian-10-r0
    postgresqlUsername: concourse
    postgresqlDatabase: concourse
    persistence:
      enabled: true
      size: 100Gi
    resources:
      requests:
        memory: 10Gi
        cpu: "4"
    primary:
      nodeSelector:
        ccloud.sap.com/nodepool: "ci-system"
      tolerations:
        - key: "ci"
          operator: Equal
          value: "system"
          effect: "NoSchedule"

  secrets:
    create: true

webhook-broadcaster:
  image: keppel.eu-de-2.cloud.sap/ccloud-dockerhub-mirror/sapcc/concourse-webhook-broadcaster
  imageTag: "0.6.3"
  pullPolicy: IfNotPresent

# Deploy Concourse Prometheus alerts.
alerts:
  enabled: true
  # Name of the Prometheus to which the alerts should be assigned to.
  prometheus: kubernetes

backup:
  enabled: false
  image: keppel.eu-de-2.cloud.sap/ccloud/backup-tools
  imageTag: v0.6.5
  interval_full: 1 hours
  #os_auth_url:
  #os_region_name:
  #os_password:
  #os_username:
  #os_user_domain:
  #os_project_name:
  #os_project_domain:

gitResourceProxy:
  enabled: true
  replicas: 10
  timeout: 60s
  debug: true
  image: keppel.eu-de-2.cloud.sap/ccloud-dockerhub-mirror/sapcc/concourse-git-resource-proxy
  imageTag: 0.5.0
  imagePullPolicy: IfNotPresent

ingress-nginx:
  controller:
    image:
      registry: keppel.eu-de-2.cloud.sap
      image: ccloud-k8sgcr-mirror/ingress-nginx/controller
      tag: "v1.1.0"
    #ingressClassByName: true
    ingressClassResource:
      name: git-proxy
    scope:
      enabled: true
    config:
      proxy-send-timeout: "300"
      proxy-read-timeout: "300"
      proxy-body-size: "0k"
      disable-ipv6: "true"
      #load-balance: "least_conn"
    service:
      enabled: false
    admissionWebhooks:
      enabled: false
  defaultBackend:
    enabled: false
