---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastiflow-query-exporter
  labels:
    system: openstack
    service: logging
    component: configuration

data:
{{ (.Files.Glob "files/*.cfg").AsConfig | indent 4 }}
  elastiflow-thousandeyes-probes.cfg: |
{{ tpl (.Files.Get "templates/_elastiflow-thousandeyes-probes.cfg.tpl") . | indent 4 }}
