apiVersion: v1
kind: Secret

metadata:
  name: k8s-frontend-additional-scrape-config
  labels:
    prometheus: k8s-frontend

data:
  scrape-config.yaml: {{ include (print $.Template.BasePath  "/_prometheus.yaml.tpl") . | b64enc }}
