apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        name: {{ .Release.Name }}
      annotations:
        checksum/bind.config: {{ include "bind/templates/config.yaml" . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "name"
                    operator: In
                    values:
                    {{ if eq .Values.name (printf "bind1-%s" (.Values.global.region)) }}- bind2-{{.Values.global.region}}{{ end }}
                    {{ if eq .Values.name (printf "bind2-%s" (.Values.global.region)) }}- bind1-{{.Values.global.region}}{{ end }}
                    {{ if eq .Values.name (printf "bind1-global-%s" (.Values.global.region)) }}- bind2-global-{{.Values.global.region}}{{ end }}
                    {{ if eq .Values.name (printf "bind2-global-%s" (.Values.global.region)) }}- bind1-global-{{.Values.global.region}}{{ end }}
              topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "name"
                    operator: In
                    values:
                    {{ if eq .Values.name (printf "bind1-%s" (.Values.global.region)) }}- bind2-{{.Values.global.region}}{{ end }}
                    {{ if eq .Values.name (printf "bind2-%s" (.Values.global.region)) }}- bind1-{{.Values.global.region}}{{ end }}
                    {{ if eq .Values.name (printf "bind1-global-%s" (.Values.global.region)) }}- bind2-global-{{.Values.global.region}}{{ end }}
                    {{ if eq .Values.name (printf "bind2-global-%s" (.Values.global.region)) }}- bind1-global-{{.Values.global.region}}{{ end }}
              topologyKey: "topology.kubernetes.io/zone"
      containers:
      - name: {{ .Release.Name }}
        image: {{.Values.image_bind}}:{{ .Values.image_bind_tag}}
        imagePullPolicy: {{ .Values.image_pullPolicy }}
        ports:
          - name: dns-tcp
            containerPort: 53
            protocol: TCP
          - name: dns-udp
            containerPort: 53
            protocol: UDP
          - name: rndc-tcp
            containerPort: 953
            protocol: TCP
        volumeMounts:
          - name: persistent-storage
            mountPath: /var/lib/bind
          - name: bind-conf
            mountPath: /etc/bind
        livenessProbe:
          exec:
            command:
              - sh
              - /etc/bind/healthz
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - sh
              - /etc/bind/healthz
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
      - name: metric
        image: {{.Values.image_bind_exporter}}:{{ .Values.image_bind_exporter_tag}}
        imagePullPolicy: {{ .Values.image_pullPolicy }}
        ports:
          - name: metrics
            containerPort: 9119
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      - name: bind-conf
        configMap:
          name: {{ .Release.Name }}
