apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkImagesFromCorrectRegistry
metadata:
  name: imagesfromcorrectregistry
  labels:
    on-prod-ui: 'false' # TODO: enable after testing
spec:
  enforcementAction: dryrun
  parameters:
    registry: {{.Values.global.registry | required ".Values.global.registry not found"}}
    registryAlternateRegion: {{.Values.global.registryAlternateRegion | required ".Values.global.registryAlternateRegion not found"}}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
