apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkHighCPURequests
metadata:
  name: highcpurequests
  labels:
    on-prod-ui: 'true'
spec:
  enforcementAction: dryrun
  parameters: {}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod", "DaemonSet"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet"]
