apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkVulnerableImages
metadata:
  name: vulnerableimages
  labels:
    on-prod-ui: 'false'
spec:
  enforcementAction: dryrun # change to "deny" to enforce
  parameters: {}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
