image:
  repository: hub.global.cloud.sap/monsoon/ns-exporter
  tag: v0.6.2

concurrency: 1
interval: "1m"

#authURL:
username: ns-exporter
userDomainName: Default
#password:
projectName: cloud_admin
projectDomainName: ccadmin
