apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind2-global
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bind2-global
        component: designate
      annotations:
        checksum/bind2-global.config: {{ include "dns/charts/bind2_global/templates/config.yaml" . | sha256sum }}
    spec:
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: {{ .Values.global.region}}{{ .Values.failure_domain_zone}}
      containers:
      - name: bind2-global
        image: {{.Values.image_bind}}:{{ .Values.image_bind_tag}}
        imagePullPolicy: {{ .Values.image_pullPolicy }}
        ports:
          - name: dns-tcp
            containerPort: 53
            protocol: TCP
          - name: dns-udp
            containerPort: 53
            protocol: UDP
          - name: rndc-tcp
            containerPort: 953
            protocol: TCP
        volumeMounts:
          - name: bind2-global-persistent-storage
            mountPath: /var/lib/bind
          - name: bind-conf
            mountPath: /etc/bind
        livenessProbe:
          exec:
            command:
              - sh
              - /etc/bind/healthz
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
              - sh
              - /etc/bind/healthz
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: metric
        image: {{.Values.image_bind_exporter}}:{{ .Values.image_bind_exporter_tag}}
        imagePullPolicy: {{ .Values.image_pullPolicy }}
        ports:
          - name: metrics
            containerPort: 9119
      volumes:
      - name: bind2-global-persistent-storage
        persistentVolumeClaim:
          claimName: bind2-global
      - name: bind-conf
        configMap:
          name: bind2-global
