{{- range .Values.keppel.extra_account_domains }}

kind: Ingress
apiVersion: networking.k8s.io/v1beta1

metadata:
  name: keppel-extra-{{ .hostname }}
  annotations:
    kubernetes.io/tls-acme: "true"
    disco: "true"
    ingress.kubernetes.io/configuration-snippet: |
      rewrite "/v2/$" /v2/ break;
      rewrite "/v2/(.+)" /v2/{{ .account_name }}/$1 break;

spec:
  tls:
    - secretName: tls-keppel-extra-{{ .hostname }}
      hosts: [ {{ .hostname }}.{{ $.Values.global.region }}.{{ $.Values.global.tld }} ]
  rules:
    - host: {{ .hostname }}.{{ $.Values.global.region }}.{{ $.Values.global.tld }}
      http:
        paths:
          - path: /v2/
            backend:
              serviceName: keppel-api
              servicePort: 80

{{- end }}
