replicaCount: 3

image:
  # Default upstream repository: k8s.gcr.io/metrics-server/metrics-server
  repository: keppel.eu-de-1.cloud.sap/ccloud-k8sgcr-mirror/metrics-server/metrics-server
  pullPolicy: IfNotPresent

additionalArgs:
  - --kubelet-preferred-address-types=Hostname,InternalDNS
  - --kubelet-use-node-status-port
  - --metric-resolution=15s
