apiVersion: v1
kind: ConfigMap

metadata:
  name: baremetal-temper

data:
  temper.yaml: |
    inspector:
      host: "baremetal-inspector-3.{{ .Values.global.region }}.cloud.sap"
    redfish:
      bootImage: "http://jump01.cc.{{ .Values.global.region }}.cloud.sap/repo/iso/bml_current.iso"
      user: 'support'
    netbox:
      host: "netbox.global.cloud.sap"
    openstack:
      url: "https://identity-3.{{ .Values.global.region }}.cloud.sap/v3"
      user:  {{ .Values.global.bm_temper_user }}
      domainName: "ccadmin"
      projectName: "master"      
      projectDomainName: "ccadmin"
    aci:
      user: {{ .Values.aci.apic_user }}
    arista:
      user: {{ .Values.global.arista_username }}
      transport: "https"
      port: 443
    deployment:
      image: "vsphere-7.0U1c-amd64-baremetal"
      flavor: "inspection_test"
      conductorZone: "nova-compute-ironic-testing"
      network: "cc-demo_private"
      openstack:
        url: "https://identity-3.{{ .Values.global.region }}.cloud.sap/v3"
        user: {{ .Values.global.bm_temper_user }}
        projectDomainName: "monsoon3"
        projectName: "cc-demo"      
        domainName: "monsoon3"
    rulesPath: "./etc/config/rules.json"
    domain: "cc.{{ .Values.global.region }}.cloud.sap"
    region: "{{ .Values.global.region }}"

  rules.json: |
    {
      "properties": {
        "node": [
          {
            "op": "replace",
            "path": "/name",
            "value": "{{ .node.Name }}"
          },
          {
            "op": "add",
            "path": "/driver_info/deploy_kernel",
            "value": "{{ imageToID `fedipa-kernel` }}"
          },
          {
            "op": "add",
            "path": "/driver_info/deploy_ramdisk",
            "value": "{{ imageToID `fedipa-ramdisk` }}"
          },
          {
            "op": "add",
            "path": "/properties/serial",
            "value": "{{ .node.InspectionData.Inventory.SystemVendor.SerialNumber }}"
          },
          {
            "op": "add",
            "path": "/properties/manufacturer",
            "value": "{{ .node.InspectionData.Inventory.SystemVendor.Manufacturer }}"
          },
          {
            "op": "add",
            "path": "/properties/model",
            "value": "{{ .node.InspectionData.Inventory.SystemVendor.ProductName }}"
          },
          {
            "op": "add",
            "path": "/properties/capabilities",
            "value": "boot_mode:uefi"
          },
          {
            "op": "add",
            "path": "/properties/root_device",
            "value": {
              "size": "<= {{ getRootDeviceSize }}"
            }
          },
          {
            "op": "replace",
            "path": "/resource_class",
            "value": "{{ getMatchingFlavorForNode }}"
          }
        ],
        "port": [
          {
            "op": "add",
            "path": "/local_link_connection/switch_id",
            "value": "aa:bb:cc:dd:ee:ff"
          },
          {
            "op": "add",
            "path": "/local_link_connection/port_id",
            "value": "Etherneth1/15"
          },
          {
            "op": "add",
            "path": "/local_link_connection/switch_info",
            "value": "{{ .node.Name }}"
          },
          {
            "op": "replace",
            "path": "/pxe_enabled",
            "value": true
          },
          {
            "op": "add",
            "path": "/portgroup_uuid",
            "value": "{{ getPortGroupUUID (printf `pg_%s` .node.Name)}}"
          }
        ]
      } 
    }