{{- if .Values.backup.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullName" . }}-backup-metrics
  labels:
    app: {{ include "fullName" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9188"
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
spec:
  clusterIP: None
  ports:
    - name: backup-metrics
      port: 9188
      protocol: TCP
  selector:
    app: {{ include "fullName" . }}
{{- end }}
