{{ if eq .Values.disable_tls false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-mysql-cluster-ssl
  namespace: {{ .Release.Namespace }}
  labels:
    system: openstack
    type: database
    component: {{ .Values.name }}
type: kubernetes.io/tls
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-mysql-cluster-ssl-internal
  namespace: {{ .Release.Namespace }}
  labels:
    system: openstack
    type: database
    component: {{ .Values.name }}
type: kubernetes.io/tls
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""
{{ end }}
