kubernikus:
  imageTag: 672e7510818e66c2de22fbb9b2adbefbaead1e7a
  image: keppel.eu-de-1.cloud.sap/ccloud/kubernikus

  #use a dedicated serviceaccount and proper RBAC rules for this deployment
  standalone: false
  useServiceAccount: true
  includeRBAC: true
  k8sniff:
    useRBAC: true

  api:
    policyFile: /etc/kubernikus/policy-ccadmin.json
  operator:
    nodeAffinity: false
    controllers: [groundctl, deorbiter, migration, servicing, certs]
  ingress:
    annotations:
      disco: "true"
kubernikus-dex:
  namespaceOverride: kubernikus
