apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gkownerinfoonhelmreleases
spec:
  crd:
    spec:
      names:
        kind: GkOwnerInfoOnHelmReleases
      validation:
        openAPIV3Schema:
          properties: {}

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package ownerinfoonhelmreleases

        violation[{"msg": msg}] {
          obj := input.review.object
          obj.kind == "ConfigMap"

          # If data.maintainers defines at least one maintainer then ConfigMap will have the
          # 'primary-maintainer' label defined.
          not obj.metadata.labels["primary-maintainer"]
          release_name := obj.metadata.annotations["meta.helm.sh/release-name"]
          msg := sprintf(
            "Helm release %q either doesn't use owner-info sub-chart or %q is not defined in the chart's Values.yaml file",
            [release_name, "owner-info.maintainers"],
          )
        }
