{{- if .Values.doop_agent.enabled }}
kind: Deployment
apiVersion: apps/v1

metadata:
  name: doop-agent

spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: doop-agent
  template:
    metadata:
      labels:
        name: doop-agent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/targets: kubernetes
    spec:
      enableServiceLinks: false
      containers:
        - name: parser
          image: {{.Values.global.registry | required ".Values.global.registry"}}/doop-agent:{{.Values.doop_agent.image_tag}}
          imagePullPolicy: IfNotPresent
          args: [ '-container', 'doop-agent', '-object', {{.Values.global.region | required ".Values.global.region" | quote}} ]
          env:
            - name: OS_AUTH_URL
              value: 'https://identity-3.{{.Values.doop_agent.target_region | required ".Values.doop_agent.target_region"}}.cloud.sap/v3'
            - name: OS_AUTH_VERSION
              value: '3'
            - name: OS_IDENTITY_API_VERSION
              value: '3'
            - name: OS_PROJECT_DOMAIN_NAME
              value: ccadmin
            - name: OS_PROJECT_NAME
              value: master
            - name: OS_REGION_NAME
              value: {{.Values.doop_agent.target_region | required ".Values.doop_agent.target_region" | quote}}
            - name: OS_USER_DOMAIN_NAME
              value: {{.Values.doop_agent.upload_user_domain_name | required ".Values.doop_agent.upload_user_domain_name" | quote}}
            - name: OS_USERNAME
              value: {{.Values.doop_agent.upload_user_name | required ".Values.doop_agent.upload_user_name" | quote}}
            - name: OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: doop-agent
                  key: upload_password
          ports:
            - name: metrics
              containerPort: 8080
          resources:
            requests:
              cpu: "25m"
              memory: "64Mi"
            limits:
              cpu: "25m"
              memory: "64Mi"
          securityContext:
            allowPrivilegeEscalation: false
{{- end }}
