apiVersion: v1
kind: Service
metadata:
  name: redfish-exporter
  namespace: infra-monitoring
  labels:
    app: redfish-exporter
    type: exporter
spec:
  selector:
    app: redfish-exporter
  ports:
    - port: {{ .Values.redfish.listen_port }}
