unbound:
  image_unbound: ccloud/unbound
  image_unbound_exporter: ccloud/unbound_exporter
  image_unbound_tag: latest 
  image_unbound_exporter_tag: latest 
  image_pullPolicy: IfNotPresent
  port_unbound_exporter: 9107
  interface: 0.0.0.0
  failure_domain_zone: a

alerts:
  # Name of the Prometheus to which the alerts should be assigned to.
  prometheus: openstack
