{{- if .Values.hotrod.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jaeger.fullname" . }}-hotrod
  labels:
    app: {{ template "jaeger.name" . }}
    jaeger-infra: hotrod-deployment
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: hotrod
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.hotrod.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "jaeger.name" . }}
        component: hotrod
        release: {{ .Release.Name }}
        jaeger-infra: hotrod-instance
    spec:
      containers:
        - name: {{ template "jaeger.fullname" . }}-hotrod
          args: ["all", "-a", "profiler-jaeger-agent:6831"]
          image: {{ .Values.hotrod.image.repository }}:{{ .Values.hotrod.image.tag }}
          imagePullPolicy: {{ .Values.hotrod.image.pullPolicy }}
          env:
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - containerPort: {{ .Values.hotrod.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.hotrod.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.hotrod.service.internalPort }}
          resources:
{{ toYaml .Values.hotrod.resources | indent 12 }}
    {{- if .Values.hotrod.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.hotrod.nodeSelector | indent 8 }}
    {{- end }}
{{- end }}
