{{ if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: toolbox-init
  labels:
    type: configuration
    app: toolbox
data:
  toolbox-init.sh: |
{{ include (print .Template.BasePath "/etc/_toolbox_init.tpl") . | indent 4 }}
{{- end }}