kind: Ingress
apiVersion: networking.k8s.io/v1beta1

metadata:
  name: barbican-api
  namespace:  {{.Release.Namespace}}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    system: openstack
    type: api
    component: barbican
  {{- if .Values.tlsacme }}
  annotations:
    kubernetes.io/tls-acme: "true"
  {{- end }}
spec:
  tls:
     - secretName: tls-{{ include "barbican_api_endpoint_host_public" . | replace "." "-" }}
       hosts: [{{include "barbican_api_endpoint_host_public" .}}]
  rules:
    - host: {{include "barbican_api_endpoint_host_public" .}}
      http:
        paths:
        - path: /
          backend:
            serviceName: barbican-api
            servicePort: {{.Values.api_port_internal}}
