apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blackhole

spec:
  tls:
     - secretName: blackhole
       hosts: [{{ .Values.ingress.host }}]
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: blackhole
              servicePort: 80
