docker_repo: keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/prom/snmp-exporter
image_version: v0.20.0
global:
  n7k:
    enabled: false
  asa:
    enabled: false
snmp_exporter:
  listen_port: 9116
  replicas: 2
  scrapeInterval: 1m
  scrapeTimeout: 55s
  fullnameOverride: snmp-exporter
  arista:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
      priv_password: DEFINED-IN-REGION-SECRECTS
  asr:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  asr03:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  asr04:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  asa:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  f5:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  n3k:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  n7k:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  pxdlrouternxos:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    alerts:
      enabled: false
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  acileaf:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  n9kpx:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  ipn:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  acispine:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  acistretch:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  ucs:
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  hsm:
    enabled: false
    version: DEFINED-IN-REGION-SECRECTS
    community: DEFINED-IN-REGION-SECRECTS
    snmpv3:
      enabled: false
      version: DEFINED-IN-REGION-SECRECTS
      security_level: DEFINED-IN-REGION-SECRECTS
      username: DEFINED-IN-REGION-SECRECTS
      password: DEFINED-IN-REGION-SECRECTS
      auth_protocol: DEFINED-IN-REGION-SECRECTS
      priv_protocol: DEFINED-IN-REGION-SECRECTS
  alerts:
    enabled: false
    prometheus: DEFINED-IN-REGION-SECRETS
