prometheus:
  image: prom/prometheus
  tag: v2.2.1

retention: 7d

persistence:
  name: prometheus-frontend-data
  accessMode: ReadWriteMany
  size: 300Gi

alerting:
  # disable all alerts by setting `false` here
  enabled: true
  # disable kubernetes alerts by setting `false` here
  kubernetes: true
  # disable openstack alerts by setting `false` here
  openstack: true
  # disable baremetal alerts by setting `false` here
  baremetal: true
