{{- $domains := list "ccadmin" "bs" "fsn" "hcm" "hcp03" "hec" "monsoon3" "s4" "wbs"}}
apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: cinder-support-seed
  labels:
    app: "cinder"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: volume
    type: seed
spec:
  requires:
  - monsoon3/cinder-seed
  {{- range $domains }}
  - monsoon3/domain-{{ . | lower }}-seed
  {{- end }}

  domains:
  {{- range $domains }}

  - name: {{ . | lower }}
    groups:
    - name: {{ . | upper }}_API_SUPPORT
      roles:
      - project: api_support
        role: volume_admin
      - domain: {{ . | lower }}
        role: volume_admin
        inherited: true
    - name: {{ . | upper }}_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: volume_admin
      - domain: {{ . | lower }}
        role: volume_viewer
        inherited: true
    - name: {{ . | upper }}_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: volume_admin
      - domain: {{ . | lower }}
        role: volume_viewer
        inherited: true
    - name: {{ . | upper }}_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: volume_admin
      - domain: {{ . | lower }}
        role: volume_admin
        inherited: true
    - name: {{ . | upper }}_SERVICE_DESK
      roles:
      - project: service_desk
        role: volume_admin
      - domain: {{ . | lower }}
        role: volume_viewer
        inherited: true
  {{- end }}
