dependencies:
  - name: cc-rbac
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.1
  - name: go-pmtud
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.3
  - name: kube-dns
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.3.2
  - condition: kube-fip-controller.enabled
    name: kube-fip-controller
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.7
  - name: kube-proxy
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.6.14
  - name: kubernikus-rbac
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.2.1
  - name: prometheus-crds
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.0
