# Default values for blackbox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jump_host_floating_ip: DEFINED-IN-REGION-SECRETS
server_fixed_ips: DEFINED-IN-REGION-SECRETS
server_floating_ips: DEFINED-IN-REGION-SECRETS
server_dns_names: DEFINED-IN-REGION-SECRETS
server_nfs_floating_ips: DEFINED-IN-REGION-SECRETS
lbaas_floating_ips: DEFINED-IN-REGION-SECRETS
bind_ips: DEFINED-IN-REGION-SECRETS
unbound_ips: DEFINED-IN-REGION-SECRETS
regional_ptr: DEFINED-IN-REGION-SECRETS
hidden_master: DEFINED-IN-REGION-SECRETS
tsig_key: DEFINED-IN-REGION-SECRETS
ad_nodes: DEFINED-IN-REGION-SECRETS
ad_dns: DEFINED-IN-REGION-SECRETS
sleep:
  iterate: 60