apiVersion: v1
kind: ConfigMap
metadata:
  name: clair-etc
data:
  config.yaml.in: |
{{ include "clair/templates/etc/_config.yaml.tpl" | indent 4 }}
  start.sh: |
    #!/bin/sh
    set -euo pipefail
    sed "s/%POSTGRES_PASSWORD%/${POSTGRES_PASSWORD}/" < /etc/clair/config.yaml.in > /tmp/clair-config.yaml
    clair -conf /tmp/clair-config.yaml -mode combo
