apiVersion: v1
kind: Service

metadata:
  name: clair
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/targets: "openstack"

spec:
  selector:
    name: clair
  ports:
    - port: 8080
    - port: 8081
