# Default values for blackhole.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replica_count: 2
image:
  repository: sapcc/blackhole
  tag: latest
  pullPolicy: IfNotPresent

# ingress:
#   enabled: false
#   probe: true
