---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-query-exporter
  labels:
    system: openstack
    service: logging
    component: configuration

data:
{{ (.Files.Glob "files/*.cfg").AsConfig | indent 4 }}
