apiVersion: v2
name: gatekeeper
description: OPA Gatekeeper deployment for sapcc
type: application
version: 1.0.0 # please leave like this; this does not use Chartmuseum

dependencies:
  - name: gatekeeper
    alias: gatekeeper-upstream
    version: 3.4.1
    repository: https://open-policy-agent.github.io/gatekeeper/charts
  - name: owner-info
    repository: file://../../common/owner-info
    version: 0.1.0
