apiVersion: v2
name: gatekeeper
description: OPA Gatekeeper deployment for sapcc
type: application
version: 0.1.0

dependencies:
  - name: gatekeeper
    alias: gatekeeper-upstream
    version: 3.4.0-rc.1
    repository: file://vendor/gatekeeper
