# documentation for this section: <https://github.com/open-policy-agent/gatekeeper/tree/master/charts/gatekeeper>
gatekeeper-upstream:
  createNamespace: false
  constraintViolationsLimit: 100
  disableValidatingWebhook: true # TODO enable
  logDenies: true

  audit:
    resources:
      limits:
        cpu: 2
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 256Mi

helm_manifest_parser:
  image_tag: 06eddf0679 # Git commit for <https://github.com/sapcc/gatekeeper-addons>

doop_agent:
  enabled: true
  image_tag: 626eb533c2 # Git commit for <https://github.com/sapcc/gatekeeper-addons>
  # values with default value null must be provided by values.yaml
  target_region: null
  upload_user_name: null
  upload_user_domain_name: null
  upload_password: null
