# documentation for this section: <https://github.com/open-policy-agent/gatekeeper/tree/master/charts/gatekeeper>
gatekeeper-upstream:
  createNamespace: false
  constraintViolationsLimit: 100
  disableValidatingWebhook: true # TODO enable
  logDenies: true

helm_manifest_parser:
  image_tag: acc951ea36 # Git commit for <https://github.com/sapcc/gatekeeper-addons>
