{{- if .Values.global.arista_exporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: arista-exporter
spec:
  selector:
    app: arista-exporter
    type: exporter
  ports:
    - port: 9200
{{- end }}