dependencies:
  - name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.28.2
  - name: conntrack-nanny
    repository: file://vendor/conntrack-nanny
    version: 0.1.0
    condition: conntrack-nanny.enabled
