dependencies:
  - condition: conntrack-nanny.enabled
    name: conntrack-nanny
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.0
  - name: container-linux-update-operator
    repository: https://charts.eu-de-2.cloud.sap
    version: v0.0.1
  - name: dex
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.8.0
  - condition: disco.enabled
    name: disco
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.3.5
  - name: kubernetes-dashboard
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.6.1
  - name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 0.28.2
  - name: node-problem-detector
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.3.2
  - name: sysctl
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.1
  - name: vice-president
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.1.4
