# Disabled by default until the transition to the operated Prometheus was done.
enabled: false

# Name of the Prometheus to which the rules should be assigned to.
prometheusFrontendName: k8s-frontend
prometheusCollectorName: k8s-collector
