image:
  repository: prom/alertmanager
  tag: v0.15.2

global:
  region: DEFINED-IN-SECRETS
  domain: DEFINED-IN-SECRETS

cluster:
  listen_address: DEFINED-IN-SECRETS
  peer_timeout: 30s
  probe_timeout: 5s
  tcp_timeout: 30s
  # peers:
  #   - DEFINED-IN-SECRETS

slack:
  webhook_url: DEFINED-IN-SECRETS

pagerduty:
  service_key: DEFINED-IN-SECRETS

pagerduty_hypervisor:
  service_key: DEFINED-IN-SECRETS

# creates <tier>-{info, warning, critical} routing and receivers
tiers:
  - kubernetes
  - kubernikus
  - openstack
  - baremetal

# creates openstack-<service> routing and receivers
openstack_services:
  - arc
  - backup
  - barbican
  - cinder
  - designate
  - elektra
  - elk
  - ironic
  - keystone
  - limes
  - lyra
  - maia
  - manila
  - neutron
  - nova
  - swift
