# Defined in secrets.
#  global:
#    region:
#    domain:
#    clusterType: controlplane

prometheus-server:
  image:
    repository: prom/prometheus
    tag: v2.8.0

  name: k8s-frontend

  retentionTime: 1h

  additionalScrapeConfigs:
    name: k8s-frontend-additional-scrape-config
    key: scrape-config.yaml

  ingress:
    enabled: true
    host: prometheus-frontend-operated

  persistence:
    enabled: false
    size: 300Gi

  rbac:
    create: false

  serviceAccount:
    create: false
    name: default

  # The log level of the Prometheus.
  logLevel: info
