kubernikus:
  imageTag: df436eb8b4529be87c04a8812059be6e78ba1faf
  image: keppel.eu-de-1.cloud.sap/ccloud/kubernikus

  #use a dedicated serviceaccount and proper RBAC rules for this deployment
  standalone: false
  useServiceAccount: true
  includeRBAC: true
  k8sniff:
    useRBAC: true

  api:
    policyFile: /etc/kubernikus/policy-ccadmin.json
  operator:
    nodeAffinity: false
  ingress:
    annotations:
      disco: "true"
kubernikus-dex:
  namespaceOverride: kubernikus
