kubernikus:
  imageTag: 359dec972a03c720fce6c44e89f5cac3e43c99d2

  #use a dedicated serviceaccount and proper RBAC rules for this deployment
  standalone: false
  useServiceAccount: true
  includeRBAC: true
  k8sniff:
    useRBAC: true

  api:
    policyFile: /etc/kubernikus/policy-ccadmin.json
  operator:
    nodeAffinity: false
  ingress:
    annotations:
      disco: "true"
kubernikus-dex:
  namespaceOverride: kubernikus
