{{- if .Values.simulator.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cronus-simulator-tests
  namespace: {{ .Release.Namespace }}
  labels:
    app: cronus-simulator
    chart: cronus-simulator
    release: cronus-simulator
    heritage: {{ .Release.Service }}
data:
  tests.json: |
    { 
        "catalogTests": [
            {
                "Id":        1,
                "Component": "cronus",
                "Action":    "send-sesV1",
                "Alert":     false,
                "Init":      false,
                "ConcurrentRuns": 1,
                "ConcurrentDelaySeconds": 1
            },
            {
                "Id":        2,
                "Component": "cronus",
                "Action":    "send-sesV2",
                "Alert":     false,
                "Init":      false,
                "ConcurrentRuns": 1,
                "ConcurrentDelaySeconds": 1
            },
            {
                "Id":        3,
                "Component": "cronus",
                "Action":    "list-email-identities-sesV1",
                "Alert":     false,
                "Init":      false,
                "ConcurrentRuns": 1,
                "ConcurrentDelaySeconds": 1
            },
            {
                "Id":        4,
                "Component": "cronus",
                "Action":    "list-email-identities-sesV2",
                "Alert":     false,
                "Init":      false,
                "ConcurrentRuns": 1,
                "ConcurrentDelaySeconds": 1
            },
            {
                "Id":        5,
                "Component": "cronus",
                "Action":    "send-sesV2-load",
                "Alert":     false,
                "Init":      false,
                "ConcurrentRuns": 100,
                "ConcurrentDelaySeconds": 1
            },
            {
                "Id":        6,
                "Component": "cronus",
                "Action":    "send-smtp-587",
                "Alert":     false,
                "Init":      false,
                "ConcurrentRuns": 1,
                "ConcurrentDelaySeconds": 1
            }
        ]
    }
{{- end -}}
  
