openstack-prometheus:
  name: openstack

  retentionTime: 7d

  additionalScrapeConfigs:
    name: openstack-additional-scrape-config
    key: scrape-config.yaml

  ingress:
    enabled: true
    host: prometheus-openstack

  persistence:
    enabled: true
    size: 300Gi

  serviceAccount:
    create: false
    name: default

  serviceDiscoveries:
    endpoints:
      enabled: false
