# Default values for netapp-cap-exporter.
enabled: true
fullname: netapp-capacity-exporter

prometheus:
  scrape: true
  port: 9108

apps:
  cinder:
    enabled: false
    component: "cinder"
    netappsd:
      query: bb
  baremetal:
    enabled: false
    component: "bare-metal"
    netappsd:
      query: bm
  controlplane:
    enabled: false
    component: "control-plane"
    netappsd:
      query: cp
  manila:
    enabled: false
    component: "manila"
    resources:
      requests:
        memory: 400Mi
        cpu: 100m

exporter:
  image:
    repository: keppel.eu-de-1.cloud.sap/ccloud/netapp-api-exporter
    tag: 20201216131411-master-3a53aa2
  resources:
    requests:
      memory: 200Mi
      cpu: 100m

netappsd:
  image:
    repository: keppel.eu-de-1.cloud.sap/ccloud/netappsd
    tag: master-20210226115137-3de9dac
  resources:
    requests:
      memory: 50Mi
      cpu: 50m
