kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: sysctl
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: sysctl
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sysctl
    spec:
      hostNetwork: true
      tolerations:
      - key: "species"
        operator: "Equal"
        value: "network"
        effect: "NoSchedule"
      containers:
        - image: "{{ .Values.global.registry}}/{{ .Values.images.sysctl.image }}:{{ .Values.images.sysctl.tag }}"
          name: sysctl
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
