apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-bin
  labels:
    system: openstack
    type: configuration
    component: ironic
data:
{{- if .Values.tempest_enabled }}
  ironic-tempest-start: |
{{ .Files.Get "bin/ironic-tempest-start" | indent 4 }}
{{- end }}
