global:
  region: regionOne
  domain: evil.corp

ingress:
  tls_client_auth:
    cacrt: |
      -----BEGIN CERTIFICATE-----
      superSecretCertificate
      -----END CERTIFICATE-----

disco:
  enabled: true
  seed:
    enabled: true

  openstack:
    authURL:            https://keystone.staging.evil.corp:5000/v3
    regionName:         staging
    username:           user
    userDomainName:     Default
    password:           topSecret!
    projectName:        master
    projectDomainName:  Default
    zoneName:           staging.evil.corp.

  record: ingress.staging.evil.corp.

aws-ecr-creds-helper:
  aws:
    region: xy-xxxxx-1
    accessKeyId: xyz
    secretAccessKey: xyz
