{{- if $.Values.nginx_external }}
{{- range $cluster_id, $cluster := .Values.clusters }}
{{- range $az := $.Values.global.availability_zones }}
kind: Deployment
apiVersion: apps/v1

metadata:
  name: swift-nginx-{{ $cluster_id }}-{{ $az }}
  labels:
    release: "{{ $.Release.Name }}"
    os-cluster: {{ $cluster_id }}
spec:
  revisionHistoryLimit: 5
  {{- $replicas_az := default 2.0 (index $cluster (printf "nginx_deployment_replicas_%s" $az)) }}
  replicas: {{ $replicas_az }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      {{- if eq $replicas_az 1.0 }}
      maxUnavailable: 0
      {{- else }}
      maxUnavailable: 1
      {{- end }}
      maxSurge: 2
  selector:
    matchLabels:
      component: swift-nginx-{{ $cluster_id }}
  template:
    metadata:
      labels:
        component: swift-nginx-{{ $cluster_id }}
        from: deployment
        os-cluster: {{ $cluster_id }}
        for-service: swift-proxy-{{ $cluster_id }}
      annotations:
        checksum/nginx.bin: {{ include "swift/templates/nginx-bin-configmap.yaml" $ | sha256sum }}
        checksum/nginx-cluster.etc: {{ include "swift/templates/etc/nginx-cluster-configmap.yaml" $ | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/targets: {{ required ".Values.alerts.prometheus.openstack missing" $.Values.alerts.prometheus.openstack }}
    spec:
      # No tolerations for swift nodes
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: {{ $az }}
      affinity:
        podAntiAffinity:
          # Prefere to be scheduled on nodes not yet running this proxy from a deplyoment
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - swift-nginx-{{ $cluster_id }}
                - key: from
                  operator: In
                  values:
                  - deployment
              topologyKey: "kubernetes.io/hostname"
      volumes:
        {{- tuple $cluster_id | include "swift_nginx_volumes" | indent 8 }}
      containers:
        {{- tuple "false" $cluster $ | include "swift_nginx_containers" | indent 8 }}

---
{{- end }}
{{- end }}
{{- end }}
