{{- range $cluster_id, $cluster := .Values.clusters }}
{{- if $cluster.proxy_deployment_enabled }}
kind: Deployment
apiVersion: apps/v1

metadata:
  name: swift-proxy-{{$cluster_id}}
  labels:
    release: "{{$.Release.Name}}"
    os-cluster: {{$cluster_id}}
spec:
  revisionHistoryLimit: 5
  replicas: {{ required "proxy_deployment_replicas is required" $cluster.proxy_deployment_replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      {{- if eq $cluster.proxy_deployment_replicas 1.0 }}
      maxUnavailable: 0
      {{- else }}
      maxUnavailable: 1
      {{- end }}
      maxSurge: 2
  selector:
    matchLabels:
      component: swift-proxy-{{$cluster_id}}
  template:
    metadata:
      labels:
        component: swift-proxy-{{$cluster_id}}
      annotations:
        checksum/swift-cluster.etc: {{ include "swift/templates/etc/cluster-configmap.yaml" $ | sha256sum }}
        {{- include "swift_conf_annotations" $ | indent 8 }}
        checksum/swift.bin: {{ include "swift/templates/bin-configmap.yaml" $ | sha256sum }}
        {{- include "swift_ring_annotations" $ | indent 8 }}
        {{- if $.Values.health_exporter }}
        # Prometheus annotations for the swift-health-exporter, the annotations
        # for the statsd-exporter are on the proxy-service level instead
        prometheus.io/scrape: "true"
        prometheus.io/port: "9520"
        prometheus.io/targets: {{ required ".Values.alerts.prometheus.openstack missing" $.Values.alerts.prometheus.openstack }}
        {{- end }}
    spec:
      {{- if $cluster.proxy_deployment_to_storage_nodes }}
      {{- include "swift_daemonset_tolerations" $ | indent 6 }}
      nodeSelector:
        species: {{ $.Values.species }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - swift-proxy-{{$cluster_id}}
            topologyKey: "kubernetes.io/hostname"
      volumes:
        {{- tuple $cluster_id | include "swift_proxy_volumes" | indent 8 }}
      containers:
        {{- tuple "deployment" $cluster $ | include "swift_proxy_containers" | indent 8 }}

---
{{- end }}
{{- end }}
